
data_train:
  type: &datasetclass ccmlutils.datasets.imageflowdataset.ImageFlowDataset
  filepath: &datapath /path/to/fruits-360_dataset/fruits-360
  classes: &classes
    - Avocado
    - Banana
  sub_dir: Training
  rescale: &rescale 0.00392156862745098 # 1/255.
  target_size: &target_size [100, 100]
  batch_size: 16
  shuffle: true
  set_name: train

data_validation:
  type: *datasetclass
  filepath: *datapath
  classes: *classes
  sub_dir: Test
  rescale: *rescale
  target_size: *target_size
  batch_size: 16
  shuffle: false
  set_name: validation

data_test:
  type: *datasetclass
  filepath: *datapath
  classes: *classes
  sub_dir: Test
  rescale: *rescale
  target_size: *target_size
  batch_size: 16
  shuffle: false
  set_name: test


data_train_eval:
  type: *datasetclass
  filepath: *datapath
  classes: *classes
  sub_dir: train
  rescale: *rescale
  target_size: *target_size
  batch_size: 16
  shuffle: false
  set_name: train