
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`
example_test_data_ratio: 0.2
example_num_train_iter: 10000
example_learning_rate: 0.01
train_data_name: iris

epochs: 10

callbacks:
  - type: samplemlproject.callbacks.callback_factories.model_callback_factory
    params:
      filepath: experiment_outputs/$RUN_ID/models/$RUN_ID-model-ep{epoch:03d}.hdf5
  - type: samplemlproject.callbacks.callback_factories.logging_callback_output
    params:
      filename: experiment_outputs/$RUN_ID/logs/train_logs.csv

optimizer:
  type: keras.optimizers.RMSprop
  params:
    lr: 0.0001
    decay: 0.000001

n_classes: 1
scaling: 0.00392156862745098 # 1/255.
input_shape: [100, 100, 3]

