
# Number of training epochs
epochs: 10

# Callbacks used for training
# $RUN_ID is replaced with a timestring
# $SHORT_ID is a alphanumeric hash value of the $RUN_ID (easier to remember and search for)
callbacks:
  - type: samplemlproject.callbacks.callback_factories.model_callback_factory
    params:
      filepath: experiment_outputs/$RUN_ID-id_$SHORT_ID/models/$SHORT_ID-model-ep{epoch:03d}.hdf5
  - type: samplemlproject.callbacks.callback_factories.logging_callback_output
    params:
      filename: experiment_outputs/$RUN_ID-id_$SHORT_ID/logs/train_logs.csv

# Optimizer is used in the experiment
optimizer:
  type: keras.optimizers.RMSprop
  params:
    lr: 0.0001
    decay: 0.000001

# With n_classes = 1 the binary crossentropy is used. Otherwise use the same number of classes as in your dataset
n_classes: 1
# input_shape for building the model
input_shape: [100, 100, 3]

